- hosts: all
  become: yes
  tasks:

    - name: update
      yum:
        name: "*"
        state: latest
    
    - name: install packages
      yum:
        name: "{{ packages }}"
        state: present 
      vars:
        packages: 
          - java-1.8.0-openjdk
          - git
          - maven 
          - python3
          - python3-pip
          - wget
          - curl      

    - name: install jenkins
      shell: |
        wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins.io/redhat/jenkins.repo
        rpm --import http://pkg.jenkins.io/redhat/jenkins.io.key
        yum install -y jenkins
        # sudo usermod -a -G docker jenkins
    
    - name: start jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes
    
    - pause: seconds=30
    - name: show initial password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: initial_pass
      
    - debug: var=initial_pass.stdout
  
    
        