variable "ecs_cluster_name"{}
variable "ecs_cluster_name"{}
#variable "ecs_public_subnet_ids"{}
variable "security_groups"{}
variable "key_name"{}
variable "subnet_id"{}
variable "user_data"{}
variable "agent_ami"{}
variable "instance_type"{}
variable "isotags"{}